const products = [
    {
      "title": "Handcrafted Bangle Box",
      "description": "Elegant handcrafted bangle box, perfect for storing your precious bangles and jewelry. Features spacious compartments and traditional design.",
      "shortDescription": "Handcrafted bangle storage box",
      "price": 499,
      "comparePrice": 599,
      "discount": 0,
      "stock": 20,
      "sku": "BB001",
      "category": "bangle-box",
      "subcategory": "storage",
      "tags": ["jewelry", "bangle", "box", "handcrafted"],
      "materials": ["Wood", "Lining Fabric"],
      "dimensions": { "length": 20, "width": 10, "height": 8, "unit": "cm" },
      "weight": { "value": 450, "unit": "g" },
      "colorVariants": [
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597791/hero_t4fi2s.png","https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597791/N-BB5_odktzi.jpg"] },
        { "name": "Blue", "hex": "#0000ff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597792/N-BB6_dzimtg.jpg","https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597791/hero_nr3bpn.png"] },
        { "name": "Cyan", "hex": "#00ffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597794/hero_ma56cw.png","https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597795/N-BB1_ngnihb.jpg"] },
        { "name": "Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597793/hero_y0xnn6.png","https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597793/N-BB2_tpjglb.jpg"] }
      ],
      "images": [
  { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597793/Copy_of_N-BB4_umolyd.jpg", "alt": "Bangle Box Front",  },
  { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597791/Copy_of_N-BB3_ohiitv.jpg", "alt": " Bangle Box Top", }
],
      "published": true,
      "featured": false,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Wipe with dry cloth. Keep away from moisture.",
      "seo": { "metaTitle": "Handcrafted Bangle Box", "metaDescription": "Premium handcrafted bangle box for jewelry storage.", "keywords": ["bangle box", "jewelry storage"] }
    },
    {
      "title": "Designer Clutch",
      "description": "Stylish clutch made from high-quality materials, suitable for parties and casual outings. Features secure closure and elegant look.",
      "shortDescription": "Designer party clutch",
      "price": 799,
      "comparePrice": 999,
      "discount": 0,
      "stock": 40,
      "sku": "CLT001",
      "category": "clutch",
      "subcategory": "bags",
      "tags": ["clutch", "party", "fashion", "designer"],
      "materials": ["Velvet", "Zipper"],
      "dimensions": { "length": 25, "width": 10, "height": 5, "unit": "cm" },
      "weight": { "value": 320, "unit": "g" },
      "colorVariants": [
        { "name": "Red", "hex": "#e74c3c", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597819/N-C1_pfnsoi.jpg"] },
        { "name": "Beige", "hex": "#f5f1eb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597818/N-C2_feixcq.jpg"] },
        { "name": "Lavender", "hex": "#b57be8", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597815/N-C10_wbdvzt.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597817/N-C4_magqcn.jpg"] },
        { "name": "Black & White", "hex": "#808080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597817/N-C5_obmvta.jpg"] },
        { "name": "Off White", "hex": "#f5f5f5", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597818/N-C3_jaivjp.jpg"] },
        { "name": "Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597816/N-C7_razxfl.jpg"] },
        { "name": "Cream", "hex": "#f5f1eb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597816/N-C8_yg4oye.jpg"] },
        { "name": "White", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597817/N-C6_axjrnm.jpg"] },
        { "name": "Golden Yellow", "hex": "#d4af37", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597815/N-C9_zznmoi.jpg"] },
        { "name": "White-1", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597815/N-C11_vqr4df.jpg"] },
        { "name": "Navy Blue", "hex": "#000080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597815/N-C12_qf7gxp.jpg"] },
        { "name": "White-2", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597814/N-C13_indsbh.jpg"] },
      ],
     "images": [
  { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597819/hero_svk4uq.png", "alt": "Designer Clutch" },

],
      "published": true,
      "featured": true,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Spot clean only.",
      "seo": { "metaTitle": "Designer Clutch", "metaDescription": "Trendy designer clutch for special occasions.", "keywords": ["clutch", "designer bag"] }
    },
    {
      "title": "Premium Gift Hamper",
      "description": "Exclusive gift hamper containing a curated selection of delightful goodies. Perfect choice for festivals, birthdays, or corporate gifting.",
      "shortDescription": "Exclusive festive gift hamper",
      "price": 1499,
      "comparePrice": 1799,
      "discount": 0,
      "stock": 10,
      "sku": "GH001",
      "category": "gift-hampers",
      "subcategory": "gifts",
      "tags": ["gift", "hamper", "festival", "premium"],
      "materials": ["Basket", "Gift Items"],
      "dimensions": { "length": 32, "width": 25, "height": 15, "unit": "cm" },
      "weight": { "value": 1200, "unit": "g" },
      "colorVariants": [
        
        { "name": "Blue", "hex": "#273c7b", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597800/GIFT_HAMPER_2_PIECE_SET_kcqgdj.jpg"] },
        { "name": "Green", "hex": "#27ae60", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597799/N-GH1_ozdvvf.jpg"] },
        { "name": "Peach", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597799/N-GH2_t9mdck.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597800/GIFT_HAMPER_2_PIECE_SET_kcqgdj.jpg", "alt": "Premium Gift Hamper"}
      ],
      "published": true,
      "featured": true,
      "isHandmade": false,
      "madeIn": "India",
      "careInstructions": "Store in a cool, dry place.",
      "seo": { "metaTitle": "Premium Gift Hamper", "metaDescription": "Curated festive gift hamper for all occasions.", "keywords": ["gift hamper", "festive gift"] }
    },
    {
      "title": "Soft Goggle Cover",
      "description": "Durable and stylish soft cover for your goggles and eyeglasses. Protects lenses from scratches and dust.",
      "shortDescription": "Protective goggle/eyeglass cover",
      "price": 199,
      "comparePrice": 299,
      "discount": 0,
      "stock": 50,
      "sku": "GC001",
      "category": "goggle-cover",
      "subcategory": "accessories",
      "tags": ["eyeglass", "goggle", "cover", "soft"],
      "materials": ["Cotton", "Foam"],
      "dimensions": { "length": 18, "width": 8, "height": 2, "unit": "cm" },
      "weight": { "value": 50, "unit": "g" },
      "colorVariants": [
        { "name": "L Grey", "hex": "#808080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597811/N-GCL1_e6nb44.jpg"] },
        { "name": "L White", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597809/N-GCL2_seqj4v.jpg"] },
        { "name": "L Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597809/N-GCL3_raxteq.jpg"] },
        { "name": "L Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597809/N-GCL4_gndbvo.jpg"] },
        { "name": "M Lavendar", "hex": "#b57be8", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597813/N-GCM1_eddvcp.jpg"] },
        { "name": "M Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597813/N-GCM3_m04ysl.jpg"] },
        { "name": "M White", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597812/N-GCM6_jbw8da.jpg"] },
        { "name": "M Black2", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597812/N-GCM4_gzhjbg.jpg"] },
        { "name": "M Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597811/N-GCM7_f0f0dt.jpg"] },
        { "name": "M Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597812/N-GCM5_zoylz4.jpg"] },
        
        { "name": "M Green", "hex": "#27ae60", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597811/N-GCM9_hzqtqh.jpg"] },
        { "name": "M Beige", "hex": "#f5f1eb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597811/N-GCM8_vaqajh.jpg"] },
        { "name": "M Orange", "hex": "#f59e0b", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597813/N-GCM2_nroydn.jpg"] },
        
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597809/N-GCL2_seqj4v.jpg", "alt": "Soft Goggle Cover",  }
      ],
      "published": true,
      "featured": false,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Hand wash recommended.",
      "seo": { "metaTitle": "Soft Goggle Cover", "metaDescription": "Protective cover for goggles and eyeglasses.", "keywords": ["goggle cover", "eyeglass soft case"] }
    },
    {
      "title": "Classic Kitty Bag",
      "description": "Compact and stylish kitty bag designed for everyday essentials. Features sturdy handles and trendy patterns, suitable for both girls and women.",
      "shortDescription": "Compact everyday kitty bag",
      "price": 349,
      "comparePrice": 499,
      "discount": 0,
      "stock": 30,
      "sku": "KTB001",
      "category": "kitty-bag",
      "subcategory": "bag",
      "tags": ["kitty", "small", "fashion", "trendy"],
      "materials": ["Canvas", "Cotton"],
      "dimensions": { "length": 22, "width": 18, "height": 6, "unit": "cm" },
      "weight": { "value": 220, "unit": "g" },
      "colorVariants": [
        { "name": "Pink", "hex": "#ffb6c1", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597859/N-K9_gao7kq.jpg"] },
        { "name": "Beige", "hex": "#f5f5dc", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597881/N-K2_hxyg5a.jpg"] },
        { "name": "Maroon", "hex": "#800000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597881/N-K3_hghfas.jpg"] },
        { "name": "Blue", "hex": "#0000ff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597880/N-K5_depcfp.jpg"] },
        { "name": "Green", "hex": "#008000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597880/N-K4_hmrixd.jpg"] },
        { "name": "Yellow", "hex": "#ffff00", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597879/N-K6_ctzzm0.jpg"] },
        { "name": "Gold", "hex": "#ffd700", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597879/N-K7_pv4mka.jpg"] },
        { "name": "Navy Blue", "hex": "#000080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597822/N-K10_d7xhsk.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597819/N-K11_e9wrfv.jpg"] },
        { "name": "Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597879/N-K8_bq8jfw.jpg"] },
        { "name": "Rose Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597859/N-K9_gao7kq.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597819/N-K11_e9wrfv.jpg", "alt": "Classic Kitty Bag" }
      ],
      "published": true,
      "featured": false,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Wipe clean with a damp cloth.",
      "seo": { "metaTitle": "Classic Kitty Bag", "metaDescription": "Trendy compact kitty bag for daily essentials.", "keywords": ["kitty bag", "small handbag"] }
    },
    {
      "title": "Long Tote Bag",
      "description": "Spacious long tote bag with sturdy shoulder straps. Ideal for shopping, travel, and daily use. Made with high-quality cotton fabric and simple modern design.",
      "shortDescription": "Large, durable tote bag",
      "price": 599,
      "comparePrice": 799,
      "discount": 0,
      "stock": 40,
      "sku": "LTB001",
      "category": "long-tote-bag",
      "subcategory": "tote",
      "tags": ["tote", "shopping", "eco-friendly", "large"],
      "materials": ["Cotton", "Canvas"],
      "dimensions": { "length": 40, "width": 35, "height": 12, "unit": "cm" },
      "weight": { "value": 350, "unit": "g" },
      "colorVariants": [
        { "name": "White", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597804/N-LTB2_fneqfq.jpg"] },
        { "name": "Navy Blue", "hex": "#000080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597804/N-LTB3_bcpohz.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597804/N-LTB1_qjqyno.jpg"] },
        { "name": "Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597803/N-LTB4_gadkaq.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597804/N-LTB3_bcpohz.jpg", "alt": "Long Tote Bag" }
      ],
      "published": true,
      "featured": true,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Hand wash with mild detergent.",
      "seo": { "metaTitle": "Spacious Long Tote Bag", "metaDescription": "Large tote bag for shopping and travel.", "keywords": ["long tote bag", "shopping tote"] }
    },
    {
      "title": "Picnic Bag",
      "description": "Functional picnic bag designed for carrying snacks, drinks, and picnic accessories. Features insulated lining and easy-carry handles for outings.",
      "shortDescription": "Insulated picnic carry bag",
      "price": 899,
      "comparePrice": 1099,
      "discount": 0,
      "stock": 15,
      "sku": "PBG001",
      "category": "picnic-bag",
      "subcategory": "travel",
      "tags": ["picnic", "travel", "insulated", "outdoor"],
      "materials": ["Polyester", "Insulated lining"],
      "dimensions": { "length": 35, "width": 25, "height": 20, "unit": "cm" },
      "weight": { "value": 700, "unit": "g" },
      "colorVariants": [
        { "name": "Beige", "hex": "#5dade2", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597809/N-PIC1_y47mss.jpg"] },
        { "name": "Green", "hex": "#27ae60", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597807/PICNIC_BAG_lerbvu.jpg"] },
        { "name": "Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597808/N-PIC3_ae6yyd.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597808/N-PIC2_tjr09t.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597808/N-PIC2_tjr09t.jpg", "alt": "Picnic Bag" }
      ],
      "published": true,
      "featured": false,
      "isHandmade": false,
      "madeIn": "India",
      "careInstructions": "Clean with a soft damp cloth.",
      "seo": { "metaTitle": "Functional Picnic Bag", "metaDescription": "Insulated picnic bag for outdoor use.", "keywords": ["picnic bag", "insulated bag"] }
    },
    {
      "title": "Traditional Potli Purse",
      "description": "Traditional Indian potli purse with intricate embroidery and drawstring closure. Perfect for ethnic events and gifting.",
      "shortDescription": "Ethnic embroidered potli purse",
      "price": 399,
      "comparePrice": 549,
      "discount": 0,
      "stock": 35,
      "sku": "PTL001",
      "category": "potli-purse",
      "subcategory": "ethnic",
      "tags": ["potli", "purse", "ethnic", "handcrafted"],
      "materials": ["Silk", "Embroidered thread", "Beads"],
      "dimensions": { "length": 15, "width": 15, "height": 15, "unit": "cm" },
      "weight": { "value": 120, "unit": "g" },
      "colorVariants": [
        { "name": "Maroon", "hex": "#800000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597798/N-PB1_vczbki.jpg"] },
        { "name": "Pink", "hex": "#ffc0cb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597798/N-PB2_ueybms.jpg"] },
        { "name": "White", "hex": "#ffffff", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597798/N-PB3_btpw1v.jpg"] },
        { "name": "Beige", "hex": "#f5f1eb", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597797/N-PB5_r9wyz3.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597796/N-PB7_osekqa.jpg"] },
        { "name": "Red", "hex": "#e74c3c", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597797/N-PB4_hq4gde.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597796/N-PB6_pmgodk.jpg", "alt": "Traditional Potli Purse"}
      ],
      "published": true,
      "featured": true,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Hand wash only. Dry in shade.",
      "seo": { "metaTitle": "Traditional Potli Purse", "metaDescription": "Embroidered ethnic potli bag.", "keywords": ["potli purse", "traditional bags"] }
    },
    {
      "title": "Trendy Sling Bag",
      "description": "Trendy sling bag for convenient hands-free carrying. Features adjustable strap and stylish prints, ideal for college and travel.",
      "shortDescription": "Adjustable strap fashion sling bag",
      "price": 549,
      "comparePrice": 749,
      "discount": 0,
      "stock": 28,
      "sku": "SLB001",
      "category": "sling-bags",
      "subcategory": "casual",
      "tags": ["sling", "bag", "trendy", "casual"],
      "materials": ["Canvas", "Polyester"],
      "dimensions": { "length": 28, "width": 20, "height": 8, "unit": "cm" },
      "weight": { "value": 250, "unit": "g" },
      "colorVariants": [
        { "name": "Yellow", "hex": "#ffff00", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597803/N-SB2_phby6z.jpg"] },
        { "name": "Pink", "hex": "#ffb6c1", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597803/N-SB1_c8iscj.jpg"] },
        { "name": "Green", "hex": "#008000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597802/N-SB5_x5ezcp.jpg"] },
        { "name": "Gold", "hex": "#ffd700", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597801/N-SB4_pky1nz.jpg"] },
        { "name": "Lavender", "hex": "#b57be8", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597801/N-SB7_rssikb.jpg"] },
        { "name": "Navy Blue", "hex": "#000080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597802/N-SB6_cxiwpd.jpg"] },
        { "name": "Black", "hex": "#000000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597800/N-SB8_zfpmvr.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597801/N-SB4_pky1nz.jpg", "alt": "Trendy Sling Bag" }
      ],
      "published": true,
      "featured": true,
      "isHandmade": false,
      "madeIn": "India",
      "careInstructions": "Spot clean with gentle soap.",
      "seo": { "metaTitle": "Trendy Sling Bag", "metaDescription": "Fashion sling bag for casual use.", "keywords": ["sling bag", "trendy casual bag"] }
    },
    {
      "title": "Velvet Clutch with Flaps",
      "description": "Luxurious velvet clutch with elegant flap closure. Designed for evening occasions and parties, combining classic style with rich colors.",
      "shortDescription": "Elegant velvet clutch bag",
      "price": 999,
      "comparePrice": 1199,
      "discount": 0,
      "stock": 12,
      "sku": "VEL001",
      "category": "velvet-clutch-with-flaps",
      "subcategory": "clutch",
      "tags": ["velvet", "clutch", "party", "evening"],
      "materials": ["Velvet", "Metallic clasp"],
      "dimensions": { "length": 20, "width": 12, "height": 5, "unit": "cm" },
      "weight": { "value": 380, "unit": "g" },
      "colorVariants": [
        { "name": "Red", "hex": "#ff0000", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597807/N-V1_gvj0bo.jpg"] },
        { "name": "Chrome Yellow", "hex": "#ffa700", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597806/N-V2_s26tci.jpg"] },
        { "name": "Light Yellow", "hex": "#ffffe0", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597805/N-V5_t8ol5o.jpg"] },
        { "name": "Golden Yellow", "hex": "#ffd700", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597804/N-V6_rs5ntw.jpg"] },
        { "name": "Navy Blue", "hex": "#000080", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597806/N-V4_b91qbk.jpg"] },
        { "name": "Royal Blue", "hex": "#4169e1", "images": ["https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597806/N-V3_o1gevt.jpg"] }
      ],
      "images": [
        { "url": "https://res.cloudinary.com/dvy1jxowv/image/upload/v1762597807/N-V1_gvj0bo.jpg", "alt": "Velvet Clutch with Flaps" }
      ],
      "published": true,
      "featured": true,
      "isHandmade": true,
      "madeIn": "India",
      "careInstructions": "Dry clean only.",
      "seo": { "metaTitle": "Velvet Clutch Bag", "metaDescription": "Elegant clutch bag for evening wear.", "keywords": ["velvet clutch", "evening bag"] }
    }
  ]
  
  export default products;
  